### Get all users
GET http://localhost:3000/users

### Get one user
GET http://localhost:3000/users/PASTE_ID_HERE

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Kabila",
  "email": "jean.kabila@example.com",
  "favoriteColor": "green",
  "birthday": "1985-03-12"
}

### Update user
PUT http://localhost:3000/users/PASTE_ID_HERE
Content-Type: application/json

{
  "firstName": "Jean",
  "lastName": "Kabila",
  "email": "jean.kabila@rdc.com",
  "favoriteColor": "red",
  "birthday": "1985-03-12"
}

### Delete user
DELETE http://localhost:3000/users/PASTE_ID_HERE
